### ISSUE TITLE
Testing and Debugging

### ISSUE THREAD

**Issue by abboahene** [abboahene/wap-music-player#10]

**Comment by htetyadanar-hyo** [comment]
Next Keyword & Back Keyword issue

- In shuffle mode, next keyword doesn't work if we arrive the last song of playlist and first song of playlist. (At that time, if we  click on next, we can move another.)
- In repeat once mode, next keyword doesn't work if we arrive the last song of playlist and first song of playlist. (At that time, if we  click on next or back, we can move only that song.)
- next keyword doesn't work anytime if we enable the repeat once mode. (Mean that nothing happens when click on next keyword)
- Even though I enable the repeat once, the song is different song when we click on either next or back.
